import "../styles/build.css";
import type { AppContext, AppInitialProps, AppProps } from "next/app";
import Head from "next/head";
import App from "next/app";
import Router from "next/router";
import { ApolloError } from "@apollo/client";
import { getToken, setToken } from "./api/token";
import cookie from 'cookie'
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="p-4 bg-black text-white mb-3 absolute w-full top-0">
        <nav className="container">Header</nav>
      </header>
      <main className="max-h-screen min-h-screen flex justify-center overflow-y-scroll pt-28 pb-96">
        <div className="container h-screen flex flex-col items-center">
          <Component {...pageProps} />
        </div>
      </main>
    </>
  );
}

const redirect = (res: AppContext['ctx']['res'], location: string) => {
  if (res) { // server
    !res.headersSent && res.writeHead(302, {
      Location: location
    }).end();
  } else { // client
    Router.push(location)
  }
}

const refresh = async (token: string) => {
  const response = await fetch(process.env.BASE_URL + "/api/session/refresh", { headers: { cookie: cookie.serialize('refresh_token', token) } });
  const data = await response.json();
  if (response.status !== 200) return undefined
  return data;
};

const auth = async () => {
  const response = await fetch(process.env.BASE_URL + "/api/session/auth", { headers: { "Authorization": `Bearer ${getToken()}` } });
  const data = await response.json();
  if (response.status === 200) return true;
  return false;
};

export const sessionConditionRedirect = async (context: AppContext): Promise<AppInitialProps> => {
  // these will be available on the server
  const { req, res } = context.ctx;
  const cookies = cookie.parse(req?.headers.cookie || "");
  const refreshToken = cookies.refresh_token

  const path = req?.url || context.ctx.pathname;
  const isProtected = (path !== '/login');

  let isLoggedIn = false;

  try {
    isLoggedIn = await auth();
  } catch (e) {
    const er: ApolloError = e as ApolloError  
    if (er.graphQLErrors?.[0]?.extensions?.code === "access-denied") {
      isLoggedIn = false;
    }
  }
  let response;
  if (!isLoggedIn) {
    // see if we can get a new access token with our refresh token cookie
    try {
      response = await refresh(refreshToken);
      if (response) isLoggedIn = true;
      setToken(response.data.access_token);
    } catch (e) {
      console.log("REFRESH ERROR: ", {e})
    }
  } 

  const appProps = await App.getInitialProps(context)
  // logged out and requests '/'
  if (!isLoggedIn && isProtected) {
    redirect(res, '/login')
    // res?.end();
    return {
      pageProps: {
        appProps
      },
    }
  }
  // logged in and requests '/login'
  else if (isLoggedIn && !isProtected) {
    redirect(res, '/')
    // res?.end();
    return {
      pageProps: {
        appProps
      },
    }
  }
  // they are in the right place
  else {
    // res?.end();
    return {
      pageProps: {
        appProps
      },
    }}

}

MyApp.getInitialProps = sessionConditionRedirect

export default MyApp;
